language: generic
services:
  - docker

env:
  global:
    DOCKER_RUN_OPTS='-e GITHUB_TOKEN -e TRAVIS_BRANCH -e TRAVI_REPO_SLUG'
    AFTER_SCRIPT=smacc_ci/gh-pages.sh
    VERBOSE_OUTPUT=false
    #CATKIN_CONFIG=--no-install
  matrix:
    - ROS_DISTRO="noetic"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz ghostscript git # these packages is for documentation generation

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
  - git clone --quiet --depth 1 https://github.com/ros-infrastructure/rosdoc_lite

script:
  - .industrial_ci/travis.sh
# DEBIAN PACKAGES GENERATION
#  - bash -c 'cd smacc_ci/packagecloud_docker/; ./build_ubuntu_16_04_kinetic.sh $GITHUB_USER $GITHUB_TOKEN $PACKAGE_CLOUD_USER $PACKAGE_CLOUD_TOKEN'
#  - bash -c 'cd smacc_ci/packagecloud_docker/; ./build_ubuntu_18_04_melodic.sh $GITHUB_USER $GITHUB_TOKEN $PACKAGE_CLOUD_USER $PACKAGE_CLOUD_TOKEN'
  - bash -c 'cd smacc_ci/packagecloud_docker/; ./build_ubuntu_20_04_noetic.sh $GITHUB_USER $GITHUB_TOKEN $PACKAGE_CLOUD_USER $PACKAGE_CLOUD_TOKEN'
