# # Base profile
# TrajectoryPlannerROS:
#   # base vel/accel profile is in robot folders
#   # tolerances (defaults)
#   yaw_goal_tolerance: 0.1
#   xy_goal_tolerance: 0.1
#   latch_xy_goal_tolerance: true
#   # forward simulation
#   sim_time: 1.0
#   sim_granularity: 0.025
#   angular_sim_granularity: 0.025
#   vx_samples: 3
#   vtheta_samples: 10
#   # scoring (defaults)
#   meter_scoring: true
#   pdist_scale: 8.0
#   gdist_scale: 12.0
#   occdist_scale: 0.1
#   heading_lookahead: 0.325
#   heading_scoring_timestep: 0.8
#   heading_scoring: true
#   dwa: false
#   # other
#   oscillation_reset_dist: 0.05
#   # debug
#   publish_cost_grid_pc: false
