# obstacles:
#   observation_sources: base_scan
#   base_scan:
#     data_type: LaserScan
#     topic: base_scan
#     marking: true
#     clearing: true
#     obstacle_range: 4.0
#     raytrace_range: 5.0
#     min_obstacle_height: 0.25
#     max_obstacle_height: 0.3
#   z_voxels: 16
#   z_resolution: 0.125
#   max_obstacle_height: 2.0

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: front_laser, data_type: LaserScan, topic: front/scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 10.5, raytrace_range: 3.0}
